"""3.2.0

Revision ID: 94fd79b538dd
Revises: a37c9066592f
Create Date: 2024-09-17 11:44:45.991081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94fd79b538dd'
down_revision = 'a37c9066592f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
